product/urls.py
from django.urls import path

from .views import productpage, addproduct, finalcart, searchbar, addwishlist, deletecart, product_detail, Checkout, ConfirmOrder, myorders, send_mail, searchbrand, delete_all_cart, CompareProduct, CompareView
from .views import  tracking, delete_compare_list, track, rating

app_name = 'product'

urlpatterns = [
    path('product-page/', productpage, name = 'productpage'),
    path('addproduct/', addproduct, name = 'addproduct'),
    path('finalcart/', finalcart, name = 'finalcart'),
    path('searchbar/', searchbar, name = 'searchbar'),
    path('addwishlist/', addwishlist, name = 'wishlist'),
    path('deletecart/<int:id>', deletecart, name = 'deletecart'),
    path('product_detail/<slug>', product_detail, name = 'product_detail'),
    path('checkout/', Checkout, name = 'checkout'),
    path('confirmorder/', ConfirmOrder, name = 'confirmorder'),
    path('myorders/', myorders, name = 'myorders'),
    path('send_mail/', send_mail, name = 'send_mail'),
    path('searchbrand/', searchbrand, name = 'searchbrand'),
    path('delete_all_cart/', delete_all_cart, name = 'cart_delete'),
    path('compare-product/', CompareProduct, name = 'compareproduct'),
    path('compare-view/', CompareView, name = 'compareview'),
    path('rating/<int:id>', rating, name = 'rating'),
    path('tracking/', tracking, name = 'tracking'),
    path('track/<int:track>', track, name = 'track'),
    path('delete_compare_list/', delete_compare_list, name = 'delete_compare_list')
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('product/', include('product.urls', namespace = 'product')),
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length = 24)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name         = models.CharField(max_length = 24)
    category_key = models.ForeignKey(ProductCategory, on_delete = models.CASCADE )

    def __str__(self):
        return  self.name


class ProductDetail(models.Model):
    product_name        = models.CharField(max_length = 250)
    product_pic         = models.ImageField(upload_to = 'product/pic')
    product_price       = models.IntegerField()
    product_old_price   = models.IntegerField()
    product_category    = models.ForeignKey(ProductCategory, on_delete = models.CASCADE)
    product_brand       = models.ForeignKey(Brand, on_delete = models.CASCADE)
    product_description = models.TextField()
    product_stock       = models.IntegerField()
    slug                = models.SlugField()

    def __str__(self):
        return self.product_name + "  --->    Total No. Of Stock  " + str(self.product_stock)

    def trim_data(self):
        return self.product_name[:50]

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

class AddToCard(models.Model):
    user_key         = models.ForeignKey(User, on_delete = models.CASCADE)
    product_key      = models.ForeignKey(ProductDetail, on_delete = models.CASCADE)
    is_wishlist      = models.BooleanField(default = False)
    product_quantity = models.IntegerField(blank = True, null = True)

    def __str__(self):
        return str(self.product_key)

class PaymentMode(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class city(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class CourierPartner(models.Model):
    name     = models.CharField(max_length = 250)

    def __str__(self):
        return self.name

class TrackDetail(models.Model):
    courier_key         = models.ForeignKey(CourierPartner, on_delete = models.CASCADE)
    time_stamp          = models.DateField(auto_now_add = True)
    number              = models.CharField(max_length = 250)
    is_dispatch         = models.BooleanField(default = False)
    is_shipped          = models.BooleanField(default = False)
    is_delivered        = models.BooleanField(default = False)
    is_out_for_delivery = models.BooleanField(default = False)

    def __str__(self):
        return self.number


class Order(models.Model):
    order_id      = models.CharField(max_length = 5,blank=True,editable=False,unique=True,default=uuid.uuid4)
    user_key      = models.ForeignKey(User, on_delete = models.CASCADE)
    payment_key   = models.ForeignKey(PaymentMode, on_delete = models.CASCADE, blank = True, null = True)
    track_key     = models.ForeignKey(TrackDetail, on_delete = models.CASCADE, blank = True, null = True)
    product_key   = models.ForeignKey(ProductDetail, on_delete = models.CASCADE)
    quantity      = models.IntegerField()
    city_key      = models.ForeignKey(city, on_delete = models.CASCADE)
    time_stamp    = models.DateTimeField(auto_now_add = True)
    address       = models.TextField()
    first_name    = models.CharField(max_length = 100)
    last_name     = models.CharField(max_length = 100)
    email         = models.EmailField()
    phone_number  = models.IntegerField()
    total_price   = models.IntegerField()
    zip_code      = models.IntegerField()
    is_cancel     = models.BooleanField(default = False)
    is_processing = models.BooleanField(default = False)

    def __str__(self):
        return str(self.user_key)

class Compare(models.Model):
    user_key    = models.ForeignKey(User, on_delete = models.CASCADE)
    product_key = models.ForeignKey(ProductDetail, on_delete = models.CASCADE)

    def __str__(self):
        return str(self.user_key)

class Review(models.Model):
    user_key    = models.ForeignKey(User, on_delete = models.CASCADE)
    product_key = models.ForeignKey(ProductDetail, on_delete = models.CASCADE)
    rating      = models.FloatField()
    comment     = models.TextField()

    def __str__(self):
        return self.user_key.username

product/views.py
from django.shortcuts import render, redirect
from django.http import  JsonResponse
from django.contrib import messages
from django.db.models import Sum, Count
from .models import ProductDetail, ProductCategory, AddToCard, city, PaymentMode, Order, Brand, Compare, Review, TrackDetail
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.db.models import Q

# Create your views here.

def productpage(request):


    product_obj = ProductDetail.objects.all()
    category_obj = ProductCategory.objects.all()
    add_cart_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = False).count()
    add_wishlist_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = True).count()




    context = {
        'product_obj':product_obj,
        'category_obj':category_obj,
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
    }

    return render(request, 'products.html', context)

# add product while orering any item with their given specification
def addproduct(request):
    product = request.POST['product']
    quantity = request.POST['quantity']

    product_detail = ProductDetail.objects.get(id = product)
    main_quantity = product_detail.product_stock

    add_obj = AddToCard.objects.filter(user_key = request.user)

    define_count = add_obj.filter(user_key = request.user, product_key = product)
    total = add_obj.filter(user_key = request.user,product_key = product).count()


    total2 = int(quantity)
    for data in define_count:
        total2 = total2  + int(data.product_quantity)

    print(total2)

    if int(quantity) == 0:
        data = {
            'messa':'Product Should Not be Zero bastard'
        }
        return JsonResponse(data)

    elif int(quantity) > int(main_quantity):
        data = {
            'mes':"Not In Stock" +" "+ "Total Stock : " + str(main_quantity)
        }
        return JsonResponse(data)


    elif int(total2) > int(main_quantity):
        data = {
            'message':"Not in Stock",
        }
        return JsonResponse(data)


    elif int(quantity) == int(main_quantity):
        addcart_obj = AddToCard()
        addcart_obj.product_quantity = quantity
        addcart_obj.user_key = request.user
        product_instance = ProductDetail.objects.get(pk = product)
        addcart_obj.product_key = product_instance
        addcart_obj.save()
    else:
        addcart_obj = AddToCard()
        addcart_obj.product_quantity = quantity
        addcart_obj.user_key = request.user
        product_instance = ProductDetail.objects.get(pk = product)
        addcart_obj.product_key = product_instance
        addcart_obj.save()

    define_count = AddToCard.objects.filter(user_key = request.user, product_key = product)
    the_divine_thing = define_count.aggregate(total_data=Sum('product_quantity'))
    add_cart_count = add_obj.filter(user_key = request.user, is_wishlist = False).count()

    data = {
        'add_cart_count':add_cart_count,
        'main_quantity':main_quantity,
        'product_all_count':the_divine_thing['total_data'],
    }

    return JsonResponse(data)

def addwishlist(request):

    product = request.POST['product']

    if AddToCard.objects.filter(user_key = request.user, is_wishlist = True, product_key = product):
        print("nono")
    else:
        wislist_product = AddToCard()
        wislist_product.user_key = request.user
        product_instance = ProductDetail.objects.get(pk = product)
        wislist_product.product_key = product_instance
        wislist_product.is_wishlist = True
        wislist_product.save()

    add_wishlist_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = True).count()


    data = {
        'add_wishlist_count':add_wishlist_count,
    }


    return JsonResponse(data)

def finalcart(request):

    add_obj = AddToCard.objects.filter(user_key = request.user, is_wishlist = False)
    add_cart_count = add_obj.count()
    add_wishlist_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = True).count()


    context = {
        'add_obj':add_obj,
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
    }

    return render(request,'finalcart.html', context)

def searchbar(request):

    category = request.GET.get('category')

    category_data = ProductCategory.objects.filter(name = category)

    brand_obj = Brand.objects.filter(category_key__in = category_data)


    product_obj = ProductDetail.objects.filter(product_category__in = category_data)

    category_obj = ProductCategory.objects.all()
    add_cart_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = False).count()
    add_wishlist_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = True).count()

    


    context = {
        'product_obj':product_obj,
        'category_obj':category_obj,
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
        'brand_obj':brand_obj,
    }

    return render(request,'products.html', context)

def deletecart(request, id):

    AddToCard.objects.filter(pk = id).delete()
    return redirect('product:finalcart')

def product_detail(request, slug):

    add_obj = AddToCard.objects.filter(user_key = request.user)
    product_data = ProductDetail.objects.get(slug = slug)
    total = add_obj.filter(user_key = request.user,product_key = product_data).count()
    partial_count = add_obj.fimlter(user_key = request.user, product_key = product_data).aggregate(total_piece = Sum('product_quantity'))
    add_cart_count = add_obj.filter(user_key = request.user, is_wishlist = False).count()
    add_wishlist_count = add_obj.filter(user_key = request.user, is_wishlist = True).count()
    total_data_product = ProductDetail.objects.filter(slug = slug).aggregate(total_piece = Sum('product_stock'))
    review_product = Review.objects.filter(product_key = product_data)

    context = {
        'review_product':review_product,
        'product_data':product_data,
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
        'total':total,
        'partial_count':partial_count,
        'total_data_product':total_data_product,
    }

    return render(request, 'single-product.html', context)

def Checkout(request):

    data_cart = AddToCard.objects.filter(user_key = request.user)

    add_cart_count = data_cart.filter(user_key = request.user, is_wishlist = False).count()
    add_wishlist_count = data_cart.filter(user_key = request.user, is_wishlist = True).count()
    add_obj = data_cart.filter(user_key = request.user, is_wishlist = False)
    city_obj = city.objects.all()
    payment_obj = PaymentMode.objects.all()

    context = {
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
        'add_obj':add_obj,
        'city_obj':city_obj,
        'payment_obj':payment_obj,
    }

    return render(request, 'checkout.html', context)

def ConfirmOrder(request):
    if request.method == "POST":
        first_name = request.POST['fname']
        last_name = request.POST['lname']
        subtotal = request.POST['subtotal']
        quantity = request.POST.getlist('quantity')
        payment = request.POST['payment']
        email = request.POST['email']
        number = request.POST['number']
        add1 = request.POST['add1']
        add2 = request.POST['add2']
        city_data = request.POST.get('city')
        zip  = request.POST['zip']
        product = request.POST.getlist('product')

        payment_data = PaymentMode.objects.get(pk = payment)
        city_data = city.objects.get(pk = city_data)


        address = add1 + "," + add2

        for pro in product:
            product_data = AddToCard.objects.get(pk = pro)
            quantity1 = product_data.product_quantity

            product_dd = ProductDetail.objects.get(pk = product_data.product_key.id)
            product_quantity = product_dd.product_stock

            print(product_dd)

            if int(quantity1)>int(product_quantity):
                print("you cant order"+ product_dd.product_name)
            else:
                product_quantity = int(product_quantity) - int(quantity1)
                ProductDetail.objects.filter(pk = product_data.product_key.id).update(product_stock = product_quantity)
                Order.objects.bulk_create([
                         Order(user_key = request.user, payment_key = payment_data, quantity = product_data.product_quantity , city_key = city_data, address = address,
                         first_name = first_name, last_name = last_name, email = email, phone_number = number, zip_code = zip, total_price = subtotal,
                         product_key = product_dd)
                ])

        # product_data = ProductDetail.objects.filter(pk__in = product)
        # print(product_data)
        #
        # for product in product_data:
        #     print(product.id)
        #
        # payment_data = PaymentMode.objects.get(pk = payment)
        # city_data = city.objects.get(pk = city_data)
        #
        # for product in product_data:
        #     Order.objects.bulk_create([
        #             Order(user_key = request.user, payment_key = payment_data, quantity = 1, city_key = city_data, address = address,
        #             first_name = first_name, last_name = last_name, email = email, phone_number = number, zip_code = zip, total_price = subtotal,
        #             product_key = product.id
        #         )
        #     ])



        # order_obj = Order()
        # order_obj.user_key = request.user
        # order_obj.first_name = first_name
        # order_obj.last_name = last_name
        # order_obj.total_price = subtotal
        # order_obj.email = email
        # order_obj.phone_number = number
        # order_obj.address = address

product/templates/compare.html
{% extends 'sample.html' %}
{% block content %}
{% load static %}
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Compare Products</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Compare</a>
                </nav>
            </div>
        </div>
    </div>
</section>

<div class="container-fluid d-flex justify-content-center">
    <div class="row mt-5">
        {% for compare in compare_obj %}

        <div class="col-sm-6">

            <div class="card"> <img src="{{compare.product_key.product_pic.url}}" class="card-img-top" width="100%">
                <div class="card-body pt-0 px-0">
                    <div class="d-flex flex-row justify-content-between mb-0 px-3"> <small class="text-muted mt-1">STARTING AT</small>
                        <h6>₹{{compare.product_key.product_price}}</h6>
                    </div>
                    <hr class="mt-2 mx-3">
                    <div class="d-flex flex-row justify-content-between px-3 pb-4">
                        <div class="d-flex flex-column"><span class="text-muted">Name</span><small><b>{{compare.product_key.product_name}}</b></small></div>
                        <div class="d-flex flex-column">
                            <h5 class="mb-0">Rating</h5><small class="text-muted text-right">{% if compare.product_key.review_set.all %}{% for rating in compare.product_key.review_set.all %} <b> {{rating.rating}} </b>  {% endfor %}{% else %} <b>Not Yet Rated</b>{% endif %}</small>
                        </div>
                    </div>
                    <div class="d-flex flex-row justify-content-between p-3 mid">
                        <div class="d-flex flex-column"><small class="text-muted mb-1">Description</small>
                            <div class="d-flex flex-row"><img src="{% static 'img/descir.jpg' %}" width="35px" height="25px">
                                <div class="d-flex flex-column ml-1"><small>{{compare.product_key.product_description|slice:"0:180"}} <a href="{% url 'product:product_detail' compare.product_key.slug  %}"><b>read more</b></a> </small></div>
                            </div>
                        </div>

                    </div> <small class="text-muted key pl-3">Standard key Features</small>
                    <div class="mx-3 mt-3 mb-2"><button type="submit" class="btn btn-danger btn-block"><small>Add To Cart</small></button></div>
                    <form  action="{% url 'product:delete_compare_list' %}" method="post" id="compare{{forloop.counter}}">
                        {% csrf_token %}
                    <div class="mx-3 mt-3 mb-2"><button type="submit" class="btn btn-danger btn-block"><small>Remove From Compare List </small></button></div>
                    <input type="hidden" name="compare" value="{{compare.id}}">
                    </form>
                </div>
            </div>

        </div>
        {% endfor %}


    </div>
</div>

{% endblock %}

product/templates/finalcart.html
{% extends 'login.html' %}
{% block content %}
{% load static %}
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Cart</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Cart Area =================-->
{% if add_obj %}
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart in add_obj %}

                        <tr>
                            <td>
                                <div class="media">
                                    <div class="d-flex">
                                        <img src="{{cart.product_key.product_pic.url}}" alt="" style="width:100px">
                                    </div>
                                    <div class="media-body">
                                        <p>{{cart.product_key.product_name}}</p>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <h5 class="propri" id="product-price{{forloop.counter}}"  data-id="{{cart.product_key.product_price}}">₹{{cart.product_key.product_price}}</h5>
                            </td>
                            <td>
                                <h5 id="quantityproduct{{forloop.counter}}" class="proqua" data-id="{{cart.product_quantity}}" > {{cart.product_quantity}}</h5>
                            </td>
                            <td>
                                <h5 id = "productprice{{forloop.counter}}" class="productpp"> </h5>
                            </td>
                            

                            <td>
                                <a href="{% url 'product:deletecart' cart.id %}"> <i class="fa fa-times" aria-hidden="true"></i> </a>
                            </td>

                        </tr>
                        <form class="" action="{% url 'product:cart_delete' %}" method="post" class="delete_cart">
                            {% csrf_token %}
                            <input type="hidden" name="cart_delete" value="{{cart.id}}">
                        </form>
                        {% endfor %}

                        <tr class="bottom_button">
                            <td>
                                <a class="gray_btn" href="javascript:{document.getElementByClassName('delete_cart').submit()}">Update Cart</a>
                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="cupon_text d-flex align-items-center">
                                    <input type="text" placeholder="Coupon Code">
                                    <a class="primary-btn" href="#" class="subsub">Apply</a>
                                    <a class="gray_btn" href="#">Close Coupon</a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <h5>Subtotal</h5>
                            </td>
                            <td>
                                <h5 id="totalprice"> </h5>
                            </td>
                        </tr>
                        <tr class="shipping_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <h5>Shipping</h5>
                            </td>
                            <td>
                                <div class="shipping_box">
                                    <ul class="list">
                                        <li><a href="#">Flat Rate: $5.00</a></li>
                                        <li><a href="#">Free Shipping</a></li>
                                        <li><a href="#">Flat Rate: $10.00</a></li>
                                        <li class="active"><a href="#">Local Delivery: $2.00</a></li>
                                    </ul>
                                    <h6>Calculate Shipping <i class="fa fa-caret-down" aria-hidden="true"></i></h6>
                                    <select class="shipping_select">
                                        <option value="1">Bangladesh</option>
                                        <option value="2">India</option>
                                        <option value="4">Pakistan</option>
                                    </select>
                                    <select class="shipping_select">
                                        <option value="1">Select a State</option>
                                        <option value="2">Select a State</option>
                                        <option value="4">Select a State</option>
                                    </select>
                                    <input type="text" placeholder="Postcode/Zipcode">
                                    <a class="gray_btn" href="#">Update Details</a>
                                </div>
                            </td>
                        </tr>
                        <tr class="out_button_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="checkout_btn_inner d-flex align-items-center">
                                    <a class="gray_btn" href="#">Continue Shopping</a>
                                    <a class="primary-btn" href="{% url 'product:checkout' %}">Proceed to checkout</a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="cart_area">
    <div class="container">
            <img src="{% static 'img/empty_cart.png' %}" alt="" style="padding:20px;">
    </div>
</section>
{% endif %}

    <script type="text/javascript">


        var subtotal = 0
        {% for cart in add_obj %}
        $(document).find("#quantityproduct{{forloop.counter}}").each(function(){
            quantity = $(this).attr('data-id')
            product = $("#product-price{{forloop.counter}}").attr('data-id')
            total_price = parseInt(quantity)*parseInt(product)
        })
        var k = $("#productprice{{forloop.counter}}").html( total_price)
        console.log(k);
        {% endfor %}


        var total = 0
        $(".productpp").each(function(){
            skl = $(this).html()
            total = total + parseInt(skl)
        })
        $('#totalprice').html("₹" + total)


    </script>


    <script type="text/javascript">



    </script>


{% endblock %}