accounts/urls.py
from django.urls import path

from .views import login, register, home, logout

app_name = 'accounts'

urlpatterns = [
    path('Login/', login, name='login'),
    path('Register/', register, name ='register'),
    path('home/', home, name = 'home'),
    path('logout/', logout, name ='logout'),
]

product/urls.py
from django.urls import path

from .views import productpage, addproduct, finalcart, searchbar, addwishlist, deletecart, product_detail, Checkout, ConfirmOrder, myorders, send_mail, searchbrand, delete_all_cart, CompareProduct, CompareView
from .views import  tracking, delete_compare_list, track, rating

app_name = 'product'

urlpatterns = [
    path('product-page/', productpage, name = 'productpage'),
    path('addproduct/', addproduct, name = 'addproduct'),
    path('finalcart/', finalcart, name = 'finalcart'),
    path('searchbar/', searchbar, name = 'searchbar'),
    path('addwishlist/', addwishlist, name = 'wishlist'),
    path('deletecart/<int:id>', deletecart, name = 'deletecart'),
    path('product_detail/<slug>', product_detail, name = 'product_detail'),
    path('checkout/', Checkout, name = 'checkout'),
    path('confirmorder/', ConfirmOrder, name = 'confirmorder'),
    path('myorders/', myorders, name = 'myorders'),
    path('send_mail/', send_mail, name = 'send_mail'),
    path('searchbrand/', searchbrand, name = 'searchbrand'),
    path('delete_all_cart/', delete_all_cart, name = 'cart_delete'),
    path('compare-product/', CompareProduct, name = 'compareproduct'),
    path('compare-view/', CompareView, name = 'compareview'),
    path('rating/<int:id>', rating, name = 'rating'),
    path('tracking/', tracking, name = 'tracking'),
    path('track/<int:track>', track, name = 'track'),
    path('delete_compare_list/', delete_compare_list, name = 'delete_compare_list')
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('product/', include('product.urls', namespace = 'product')),
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user_key    = models.OneToOneField(User,on_delete = models.CASCADE)
    is_customer = models.BooleanField(default = False)
    is_seller   = models.BooleanField(default = False)

    def __str__(self):
        return str(self.user_key)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from .models import UserInfo
from product.models import AddToCard
# Create your views here.

def register(request):

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password != password2:
            data = {
            'username':username,
            'email':email,
            'message':'reenter password'
            }
            return render(request,'register.html',data)
        elif User.objects.filter(username = username):
            data = {
            'username':username,
            'email':email,
            'message':'Username Already Exist'
            }
            return render(request,'register.html',data)
        else:
            user1 = User.objects.create_user(username = username, password = password, email = email)

            user_obj = UserInfo()
            user_obj.user_key = user1
            user_obj.is_customer = True
            user_obj.save()

            auth.login(request, user1)
            return redirect('accounts:home')

    return render(request, 'register.html')

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user1 = auth.authenticate(username = username, password = password)
        if user1 is not None:
            auth.login(request, user1)
            if user1.userinfo.is_customer:
                return redirect('accounts:home')
            else:
                print("admin")
        else:
            return redirect('accounts:login')

    return render(request, 'login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)

    return redirect('accounts:login')

def home(request):

    add_cart_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = False).count()
    add_wishlist_count = AddToCard.objects.filter(user_key = request.user, is_wishlist = True).count()


    context = {
        'add_cart_count':add_cart_count,
        'add_wishlist_count':add_wishlist_count,
    }

    return render(request,'home.html', context)

accounts/templates/login.html
{% extends 'sample.html' %}
{% load static %}
{% block content %}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Register</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{% url 'accounts:register' %}">Register</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Login Box Area =================-->
	<section class="login_box_area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<img class="img-fluid" src="{% static 'img/login.jpg' %}" alt="">
						<div class="hover">
							<h4>New to our website?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="primary-btn" href="{% url 'accounts:register' %}">Create an Account</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner">
						<h3>Log in to enter</h3>
						<form class="row login_form" action="{% url 'accounts:login' %}" method="post" id="contactForm" novalidate="novalidate">
							{% csrf_token %}
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="name" name="username" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" id="name" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
							<div class="col-md-12 form-group">
								<div class="creat_account">
									<input type="checkbox" id="f-option2" name="selector">
									<label for="f-option2">Keep me logged in</label>
								</div>
							</div>
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="primary-btn">Log In</button>
								<a href="#">Forgot Password?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->
	{% endblock %}

accounts/templates/register.html
{% extends 'login.html' %}
{% load static %}
{% block content %}
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Login</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<section class="login_box_area section_gap">
    <div class="container">
        {% if message %}
        <div class="alert alert-danger col-mx-12" role="alert">
            {{message}}
        </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-12">
                <div class="login_form_inner">
                    <h3>Register to enter</h3>
                    <form class="row login_form" action="{% url 'accounts:register' %}" method="post" >
                        {% csrf_token %}
                        <div class="col-lg-12 form-group">
                            <input type="text" class="form-control" id="name" name="username" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'" value="{{username}}">
                        </div>
                        <div class="col-lg-12 form-group">
                            <input type="text" class="form-control" id="name" name="email" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'" value="{{email}}">
                        </div>
                        <div class="col-lg-12 form-group">
                            <input type="text" class="form-control" id="name" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        <div class="col-lg-12 form-group">
                            <input type="text" class="form-control" id="name" name="password2" placeholder="Re-enter Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="primary-btn">Register In</button>
                            <a href="{% url 'accounts:login' %}">Already Account</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/sample.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Karma Shop</title>
	<script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
	<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">


	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>

	<!-- Start Header Area -->
	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
						{% if user.is_authenticated %}
						<li class="nav-item"><a class="nav-link" href="index.html">Hey {{request.user}}</a></li>
						{% endif %}
						<li class="nav-item"><a class="nav-link" href="{% url 'accounts:home' %}">Home</a></li>
							<li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Shop</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="{% url 'product:productpage' %}">Shop Category</a></li>
									<li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>
									<li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li>
									<li class="nav-item"><a class="nav-link" href="cart.html">Shopping Cart</a></li>
									<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>
								</ul>
							</li>
							<li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Blog</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
									<li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
								</ul>
							</li>
							<li class="nav-item submenu dropdown active">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Pages</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="{% url 'product:compareview' %}">Compare Product</a></li>
									<li class="nav-item active"><a class="nav-link" href="login.html">Login</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'product:tracking' %}">Tracking</a></li>
									<li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
								</ul>
							</li>
							<li class="nav-item submenu dropdown ">
								<a href="{% url 'product:myorders' %}" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Your Orders</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="{% url 'product:myorders' %}">All orders list</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'product:tracking' %}">Track Product</a></li>
								</ul>
							</li>

						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"> <a style="color:red"><i class="fa fa-heart" id="wishlist" aria-hidden="true"> </i> <b class="wishlistcount">{% if add_wishlist_count != 0 %}{{add_wishlist_count}}{% endif %}</b> </a></li>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"><a href="{% url 'product:finalcart' %}" class="cart"><span class="ti-bag" id="cart-cursor"></span></a> <b id="countdata">{% if add_cart_count != 0 %}{{add_cart_count}}{% endif %}</b></li>
							<li class="nav-item">
								<form class="" action="index.html" method="post">
								{% csrf_token %}
								<input type="hidden" name="searchbar" value="">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
								</form>
							</li>
						</ul>
						<ul>
							{% if user.is_authenticated %}
							<a href="javascript:{document.getElementById('logout').submit()}"> <i class="fa fa-sign-out" aria-hidden="true"></i></a>
							<form  action="{% url 'accounts:logout' %}" method="post" id="logout">
								{% csrf_token %}
							</form>
							{% endif %}
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
	</header>
	<!-- End Header Area -->
	{% block content %}


	{% endblock %}
	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Us</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>Stay update with our latest</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
									 required="" type="email">


									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

									<!-- <div class="col-lg-4 col-md-4">
													<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
												</div>  -->
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Instragram Feed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
							<li><img src="img/i2.jpg" alt=""></li>
							<li><img src="img/i3.jpg" alt=""></li>
							<li><img src="img/i4.jpg" alt=""></li>
							<li><img src="img/i5.jpg" alt=""></li>
							<li><img src="img/i6.jpg" alt=""></li>
							<li><img src="img/i7.jpg" alt=""></li>
							<li><img src="img/i8.jpg" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Follow Us</h6>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->


	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="{% static 'js/gmaps.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>
<script type="text/javascript">
	$(document).on("mouseenter","#cart-cursor", function(){
		$(this).text("My Cart");
		$(this).on("mouseleave",function(){
			$(this).text("")
		})
	})

	$(document).on("mouseenter","#wishlist", function(){
		$(this).text("My Wishlist");
		$(this).on("mouseleave",function(){
			$(this).text("")
		})
	})
</script>

</html>